### PR TITLE
VeronicaTee contributors list

### PR DESCRIPTION
**Pull request by VeronicaTee**

### CODE REVIEW

**Comment by Yusuf-AH** [comment]
Please resolve conflicts.

**Comment by VeronicaTee** [comment]
> Please resolve conflicts.

Done.

**Comment by VeronicaTee** [comment]
> Please resolve conflicts.

Conflicts resolved, kindly merge. Thanks.

**Comment by VeronicaTee** [comment]
jfdf

> Please resolve conflicts.

Conflicts resolved, please merge

**Pull request merged**
